name: CI/CD - Sistema de Biblioteca
 
on: [push, pull_request]
 
jobs:
  build-and-test:
    name: Build e Testes
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
 
      - name: Build do projeto principal
        run: |
          gcc -Wall -o biblioteca \
              src/projeto.c src/main_projeto.c \
              -lm
          echo "Build principal concluído."